object Players {

    var players = mutableListOf(
            Player("Joe", "Smith", 42, true),
            Player("Jill", "Tanner", 36, true),
            Player("Bill", "Bon", 43, true),
            Player("Eva", "Gordon", 45, false),
            Player("Matt", "Gill", 40, false),
            Player("Kimmy", "Stein", 41, false),
            Player("Sammy", "Adams", 45, false),
            Player("Karl", "Saygan", 42, true),
            Player("Suzane", "Greenberg", 44, true),
            Player("Sal", "Dali", 41, false),
            Player("Joe", "Kavalier", 39, false),
            Player("Ben", "Finkelstein", 44, false),
            Player("Diego", "Soto", 41, true),
            Player("Chloe", "Alaska", 47, false),
            Player("Arfalseld", "Willis", 43, false),
            Player("Phillip", "Helm", 44, true),
            Player("Les", "Clay", 42, true),
            Player("Herschel", "Krustofski", 45, true),
            Player("Andrew", "Chalklerz", 42, true),
            Player("Pasan", "Membrane", 36, true),
            Player("Kenny", "Lovins", 35, true),
            Player("Alena", "Sketchings", 45, false),
            Player("Carling", "Seacharpet", 40, false),
            Player("Joseph", "Freely", 41, false),
            Player("Gabe", "Listmaker", 45, false),
            Player("Jeremy", "Smith", 42, true),
            Player("Ben", "Droid", 44, true),
            Player("James", "Dothnette", 41, false),
            Player("Nick", "Grande", 39, false),
            Player("Will", "Guyam", 44, false),
            Player("Jason", "Seaver", 41, true),
            Player("Johnny", "Thunder", 47, false),
            Player("Ryan", "Creedson", 43, false))

}